#!/bin/bash -x

#SBATCH --nodes=NNODES
#SBATCH --ntasks=NTASKS
#SBATCH --ntasks-per-node=24

#SBATCH --output=TEMP_OUTPUT_DIR/%j-out.txt
#SBATCH --error=TEMP_OUTPUT_DIR/%j-err.txt

#SBATCH --time=RUNTIME
#SBATCH --partition=batch

#SBATCH --mail-user thomas.fischer@ufz.de
#SBATCH --mail-type ALL

module load GCC
module load ParaStationMPI
module load PETSc
module load Python
module load Boost
module load Eigen

sub_path=cube_ht_benchmark/MODELREVISION/NTASKS
project_path=$HOME/data/$sub_path/
output_path=$WORK/$sub_path/results/${SLURM_JOB_NAME}/${SLURM_JOB_ID}/
mkdir -p $output_path
project_file=$project_path/PROJECTFILE
cp $project_file $output_path
srun ~/w/o/br_petsc/bin/ogs $project_file -o $output_path
mv TEMP_OUTPUT_DIR/${SLURM_JOB_ID}-out.txt $output_path/out.txt
mv TEMP_OUTPUT_DIR/${SLURM_JOB_ID}-err.txt $output_path/err.txt
